version: '3.1'  
services:
  proddb:
    image: mariadb
    environment:
      MYSQL_DATABASE: sunmait_blog
      MYSQL_ROOT_PASSWORD: password
    container_name: proddb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
