version: '3.1'
services:
  prod-server:
    image: prod-server
    ports:
      - 5000:3000
    build: 
      context: .
      dockerfile: docker/configs/prod/Dockerfile.server
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynetwork      

volumes:
  proddata:

networks:
  mynetwork:
    driver: bridge
