export const CHAT_CONSTANTS = {
  GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  UPDATE_MESSAGES: 'UPDATE_MESSAGES',
};


export const SAGAS_CHAT_CONSTANTS = {
  GET_CHATS: 'GET_CHATS',
  GET_MESSAGES: 'GET_MESSAGES',
};