version: '3.1'
services:
  dev-server:
    image: dev-server
    ports:
      - 5000:3000
      - 49153:49153
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/:/server/
      - ./server/logs/:/logs/
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynetwork

volumes:
  ? devdata

networks:
  mynetwork:
    driver: bridge
