export const POST_CONSTANTS = {
  GET_POST: 'GET_POST',
};

export const POST_ACTIONS = {
  GET_COMMENTS_FROM_CURRENT_POST: 'GET_COMMENTS_FROM_CURRENT_POST',
  POST_LIKE_OR_DISLIKE: 'POST_LIKE_OR_DISLIKE',
  GET_LIKE_OR_DISLIKE: 'GET_LIKE_OR_DISLIKE',
  POST_LIKE_OR_DISLIKE_SUCCESS: 'POST_LIKE_OR_DISLIKE_SUCCESS',
  GET_LIKE_OR_DISLIKE_SUCCESS: 'GET_LIKE_OR_DISLIKE_SUCCESS',
};
