export const POSTS_CONSTANTS = {
  GET_POSTS: 'GET_POSTS',
  ADD_POST: 'ADD_POST',
  LOAD_POST_IMAGE: 'LOAD_POST_IMAGE',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  SET_POSTS_FETCHING_STATUS: 'SET_POSTS_FETCHING_STATUS',
  CLEAR_POSTS_LIST: 'CLEAR_POSTS_LIST',
  CHANGE_POST: 'CHANGE_POST',
};
