export const POSTS_CONSTANTS = {
  GET_POSTS : 'GET_POSTS',
  ADD_POST : 'ADD_POST',
  LOAD_POST_IMAGE: 'LOAD_POST_IMAGE',
  SET_TEXTAREA_SELECTION_VALUES: 'SET_TEXTAREA_SELECTION_VALUES',
  INSERT_IMAGE: 'INSERT_IMAGE',
  INSERT_VIDEO: 'INSERT_VIDEO',
  INSERT_DIVIDER: 'INSERT_DIVIDER',
  UPDATE_POST : 'UPDATE_POST',
  DELETE_POST : 'DELETE_POST'
};