export const POSTS_ACTION_CONSTANTS = {
  GET_POSTS: 'GET_POSTS',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  SET_POSTS_FETCHING_STATUS: 'SET_POSTS_FETCHING_STATUS',

  ADD_POST: 'ADD_POST',

  UPDATE_POST: 'UPDATE_POST',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',

  DELETE_POST: 'DELETE_POST',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',

  CLEAR_POSTS_LIST: 'CLEAR_POSTS_LIST',

  LOAD_POST_IMAGE: 'LOAD_POST_IMAGE',

  SET_TEXTAREA_SELECTION_VALUES: 'SET_TEXTAREA_SELECTION_VALUES_SAGA',
  INSERT_IMAGE: 'INSERT_IMAGE_SAGA',
  INSERT_VIDEO: 'INSERT_VIDEO_SAGA',
  INSERT_DIVIDER: 'INSERT_DIVIDER_SAGA',
};
