export const PROFILE_ACTION_TYPES = {
  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',

  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',

  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',

  GET_CURRENT_USER_POSTS: 'GET_CURRENT_USER_POSTS',
  GET_CURRENT_USER_POSTS_SUCCESS: 'GET_CURRENT_USER_POSTS_SUCCESS',

  SET_CURRENT_USER_POSTS_FETCHING_STATUS: 'SET_CURRENT_USER_POSTS_FETCHING_STATUS',
  LOAD_USER_AVATAR: 'LOAD_USER_AVATAR',
};
