export const AUTH_CONSTANTS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  CREDENTIALS_CHECKED: 'CREDENTIALS_CHECKED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  CHANGE: 'CHANGE',
};
