export const SAGAS_POSTS_CONSTANTS = {
  GET_POSTS: 'GET_POSTS_SAGA',
  ADD_POST: 'ADD_POST_SAGA',
  LOAD_POST_IMAGE: 'LOAD_POST_IMAGE_SAGA',
  SET_TEXTAREA_SELECTION_VALUES: 'SET_TEXTAREA_SELECTION_VALUES_SAGA',
  INSERT_IMAGE: 'INSERT_IMAGE_SAGA',
  INSERT_VIDEO: 'INSERT_VIDEO_SAGA',
  INSERT_DIVIDER: 'INSERT_DIVIDER_SAGA',
  UPDATE_POST: 'UPDATE_POST_SAGA',
  DELETE_POST: 'DELETE_POST_SAGA',
};
