export const SAGAS_POSTS_CONSTANTS = {
  GET_POSTS: 'GET_POSTS_SAGA',
  ADD_POST: 'ADD_POST_SAGA',
  LOAD_POST_IMAGE: 'LOAD_POST_IMAGE_SAGA',
  UPDATE_POST: 'UPDATE_POST_SAGA',
  DELETE_POST: 'DELETE_POST_SAGA',
};
