version: '3.1'
services:
  devdb:
    image: mariadb
    environment:
      MYSQL_DATABASE: sunmait_blog_development
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3307
    volumes:
      - "./docker/configs/dev.cnf:/etc/mysql/conf.d/my.cnf"
    container_name: devdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
